name: wild

on:
  schedule:
    # Cron schedule for every 20 minutes
    - cron: "*/20 * * * *" # Runs at 0, 20, and 40 minutes past each hour
  workflow_dispatch: # Allows manual triggering if needed

jobs:
  frequent-task:
    runs-on: ubuntu-latest
    steps:
      - name: Display Current Time
        run: |
          echo "This workflow runs every 20 minutes"
          date
